---
title: "Compound Data Structure"
type: "challenge"
description: "Write multiple methods to parse a compound data structure to return values needed"
depends: "rock-paper-scissors"
ignore:
- "compound-data-structure.md"
